### ISSUE TITLE
在Linux中不可用

### ISSUE THREAD

**Issue by playasmegumin** [Kingtous/RustPlayer#1]
B站慕名而来的用户... 
环境：Archlinux X11 （KDE Plasma）使用Konsole终端可以运行播放器，可以用上下方向键和回车切换目录，但是无法用回车键播放歌曲，鼠标左右键无效

**Comment by Kingtous** [comment]
鼠标左右键是无动作的。’
这个回车键无法播放指的是播放无声音还是没动作？
会不会是按键冲突？有试过其他终端吗？然后libasound支持库？


这边测试过macOS、Windows都是可以的。我这两天找时间看看Linux环境下有没有问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kingtous/RustPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 中午1:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Kingtous/RustPlayer] 在Linux中不可用 (Issue #1)





 
B站慕名而来的用户...
 环境：Archlinux X11 （KDE Plasma）使用Konsole终端可以运行播放器，可以用上下方向键和回车切换目录，但是无法用回车键播放歌曲，鼠标左右键无效

**Comment by playasmegumin** [comment]
> 鼠标左右键是无动作的。’ 这个回车键无法播放指的是播放无声音还是没动作？ 会不会是按键冲突？有试过其他终端吗？然后libasound支持库？ 这边测试过macOS、Windows都是可以的。我这两天找时间看看Linux环境下有没有问题。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Kingtous/RustPlayer" ***@***.***&gt;; 发送时间:&nbsp;2022年3月2日(星期三) 中午1:35 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Kingtous/RustPlayer] 在Linux中不可用 (Issue #1) B站慕名而来的用户... 环境：Archlinux X11 （KDE Plasma）使用Konsole终端可以运行播放器，可以用上下方向键和回车切换目录，但是无法用回车键播放歌曲，鼠标左右键无效 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

没有动作，歌曲不会进入播放列表。
看了帮助大概试了试，其他按键都正常，只是歌曲不会加入播放列表。
库文件里有libasound.so libasound.so.2 libasound.so.2.0.0
Yakuake是同样的情况。

**Comment by Kingtous** [comment]
已更新，可以测试一下。目前如果试图播放没有成功会有信息提示。对于mp3、flac啥的都可以试一试。

commit id:961570eae20696d21700375a363c8375f03478f1

如果还是播放失败，可以把音频文件发我邮箱吗？我看看是什么问题

**Comment by playasmegumin** [comment]
更新后问题解决了，不过的确出现了播放失败的音频素材。已经将mp3文件发送到me@kingtous.cn了。
反复试图将添加失败的歌曲加入播放列表后发现错误信息直接输出在播放器页面了，已将截图一并附在邮件中。

**Comment by Kingtous** [comment]
找到问题了。这个音乐尾部信息不完整。代码里面做了catch了，可以试试哈

![image.png](https://s2.loli.net/2022/03/03/yfhuc6XM95UL7g2.png)

**Comment by playasmegumin** [comment]
好耶！它现在可以在我的电脑上正常运行了！

**Comment by Kingtous** [comment]
现在在搞自动化集成，到时候直接下Release版本就行

**Comment by Kingtous** [comment]
v1.0.1更新日志：
- 支持歌词滚动显示
- 回车点歌可以自动将下方所有歌曲添加进列表
