### ISSUE TITLE
cargo 编译报错 macOS

### ISSUE THREAD

**Issue by ma125125t** [Kingtous/RustPlayer#13]
➜  RustPlayer git:(master) cargo run
   Compiling ffmpeg-sys-next v4.4.0 (https://github.com/Kingtous/rust-ffmpeg-sys.git?branch=fix/4.4.0#2c8b9240)
   Compiling reqwest v0.11.10
error: failed to run custom build command for `ffmpeg-sys-next v4.4.0 (https://github.com/Kingtous/rust-ffmpeg-sys.git?branch=fix/4.4.0#2c8b9240)`

Caused by:
  process didn't exit successfully: `/Users/fang/Projects/RustPlayer/target/debug/build/ffmpeg-sys-next-319c6c336636ac4c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBAVUTIL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--static" "--libs" "--cflags" "libavutil"` did not exit successfully: exit status: 1
  error: could not find system library 'libavutil' required by the 'ffmpeg-sys-next' crate

  --- stderr
  Package libavutil was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libavutil.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libavutil' found
  ', /Users/fang/.cargo/git/checkouts/rust-ffmpeg-sys-7a8823067faec914/2c8b924/build.rs:704:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Kingtous** [comment]
请先brew install ffmpeg安装ffmpeg依赖，另外库已升级到ffmpeg 6.x，与brew版本一致。
