### ISSUE TITLE
无法播放flac无损格式文件

### ISSUE THREAD

**Issue by 244099121** [Kingtous/RustPlayer#2]
音频文件格式flac
MIME类型 audio/x-flas
采样率 96000
分辨率 24
音轨 2
长度 07:22 min(42459919个采样)
结果：无法找到该文件
尝试：系统内播放器正确识别播放。
![image](https://user-images.githubusercontent.com/37263156/156362810-51db658c-98e8-429d-b329-85b32313119d.png)

**Comment by Kingtous** [comment]
代码里面目前只检测mp3文件，等我有空更新一下，感谢关注

**Comment by Kingtous** [comment]
已支持FLAC播放，可以测试一下。

**Comment by Kingtous** [comment]
v1.0.1更新日志：
- 支持歌词滚动显示
- 回车点歌可以自动将下方所有歌曲添加进列表
