### ISSUE TITLE
没有声音

### ISSUE THREAD

**Issue by LUKE-GG33** [Kingtous/RustPlayer#3]
系统：Archlinux wayland
终端：Alacritty
可以运行播放器，但是无声音，cmus可正常播放且有声音。 
![0](https://user-images.githubusercontent.com/35057228/156544180-80a7df5a-4788-4e13-92cb-9eb5637db520.jpeg)

**Comment by Kingtous** [comment]
感谢反馈。目前感觉是arch系的alsa导致的

**Comment by Kingtous** [comment]
刚顺便更新了下README，尝试了下基于Debian 10的Deepin，这个没有问题。试了下Archlinux环境，复现了你这个问题，我看看是什么导致的。多半是依赖库

**Comment by Kingtous** [comment]
我这边安装了pulseaudio-alsa库后可以正常使用了。不知道你那边可以不

![image.png](https://s2.loli.net/2022/03/04/vqw2uKocjN5IhfH.png)

**Comment by LUKE-GG33** [comment]
> 我这边安装了pulseaudio-alsa库后可以正常使用了。不知道你那边可以不
> 
> ![image.png](https://s2.loli.net/2022/03/04/vqw2uKocjN5IhfH.png)

可以了，装完重启，完美解决了，感谢。

**Comment by LUKE-GG33** [comment]
![2.jpg](https://user-images.githubusercontent.com/35057228/156715921-82feea70-332d-47c2-89f7-a56941bd12d3.jpg)


又发现当播放完第一首歌曲，跳转到第二首歌曲时，没有声音输出，频谱还是在上下跳动，终端的字符也会错位。因为使用的vulkan，所以没办法截屏。

**Comment by Kingtous** [comment]
这个应该是Archlinux的问题，alsa版本太新导致的。这个是alsa没法打开输出流。

试试安装下alsa-plugins

v1.0.1更新日志：
- 支持歌词滚动显示
- 回车点歌可以自动将下方所有歌曲添加进列表

**Comment by LUKE-GG33** [comment]
> 这个应该是Archlinux的问题，alsa版本太新导致的。这个是alsa没法打开输出流

以后有没有可能支持纯alsa,如果使用pulseaudio-alsa快捷键无法调节音量，类似独占模式。尝试使用archwiki上的解决方法，失败了，可能我操作有问题。

**Comment by Kingtous** [comment]
这个我也不清楚arch系的依赖关系。debian系的不用安装pluseaudio的。我这些安装了alsa-plugins和pulseaudio-alsa库后在arch虚拟机里面没有复现出来

**Comment by Kingtous** [comment]
> > 这个应该是Archlinux的问题，alsa版本太新导致的。这个是alsa没法打开输出流
> 
> 以后有没有可能支持纯alsa,如果使用pulseaudio-alsa快捷键无法调节音量，类似独占模式。尝试使用archwiki上的解决方法，失败了，可能我操作有问题。

我虚拟机里面好像没有出现无法调节声音的问题。这个不会导致独占模式的

**Comment by LUKE-GG33** [comment]
> > > 这个应该是Archlinux的问题，alsa版本太新导致的。这个是alsa没法打开输出流
> > 
> > 以后有没有可能支持纯alsa,如果使用pulseaudio-alsa快捷键无法调节音量，类似独占模式。尝试使用archwiki上的解决方法，失败了，可能我操作有问题。
> 
> 我虚拟机里面好像没有出现无法调节声音的问题。这个不会导致独占模式的

快捷键无法调节主音量，播放器界面的音量是可以调节

**Comment by LUKE-GG33** [comment]
> 这个我也不清楚arch系的依赖关系。debian系的不用安装pluseaudio的。我这些安装了alsa-plugins和pulseaudio-alsa库后在arch虚拟机里面没有复现出来

不知道滚系统升级了什么包，突然正常了，~~就是偶尔卡顿一下~~，~~终端会跳出一些错位的字符~~（解决方法在下面）

**Comment by LUKE-GG33** [comment]
如果出现
ALSA lib pcm.c:8568:(snd_pcm_ recover) underrun occurred
可以用这个帖子的方法解决，虽然报错不太一样
https://bbs.archlinux.org/viewtopic.php?id=185736
@Kingtous
