### ISSUE TITLE
能否增加收听互联网电台的功能呢

### ISSUE THREAD

**Issue by sharkocha** [Kingtous/RustPlayer#4]
互联网电台功能挺不错的，现在没怎么找到好用的开源命令行internet radio工具

**Comment by Kingtous** [comment]
互联网电台是指？这个不知道有没有源diz ？

央广这里好像有m3u8源，我有空研究一下哈
http://ngcdn002.cnr.cn/live/jjzs/index.m3u8

**Comment by sharkocha** [comment]
> 互联网电台是指？这个不知道有没有源diz ？
> 
> 央广这里好像有m3u8源，我有空研究一下哈 http://ngcdn002.cnr.cn/live/jjzs/index.m3u8

嗯嗯，因为现在直接在电脑上存音乐来听好像比较少了，我用kde自带的elisa可以听网络电台，支持http协议的流媒体，有很多音乐频道。但是体验一般，希望能有一个命令行的工具支持，这样配置文件好迁移。

**Comment by Kingtous** [comment]
可以试试分支feat/radio，目前测试了下两个新闻m3u8电台源，可以正常播放。
现在没有打静态包，需要ffmpeg的dev依赖，arch好像直接装ffmpeg就行。
按h进入help界面后，按r打开`radio.ini`可以添加m3u8源。
项目根目录有个radio.ini，里面有两个新闻测试源，可以粘贴进去试试。
格式：
[name]\s[m3u8 url]

**Comment by sharkocha** [comment]
> 可以试试分支feat/radio，目前测试了下两个新闻m3u8电台源，可以正常播放。 现在没有打静态包，需要ffmpeg的dev依赖，arch好像直接装ffmpeg就行。 按h进入help界面后，按r打开`radio.ini`可以添加m3u8源。 项目根目录有个radio.ini，里面有两个新闻测试源，可以粘贴进去试试。 格式： [name]\s[m3u8 url]

在arch里面编译失败了，倒是装了ffmpeg，不过我不了解rust，没办法确定具体原因，主要的error显示为这个：

error: failed to run custom build command for `ffmpeg-sys-next v4.4.0`

估计是因为直接装ffmpeg不太行

**Comment by Kingtous** [comment]
> 
可以看看你系统安装的是不是`ffmpeg4.4`

我这看看能不能静态编译。另外我有个manjaro，我有空看看要装什么依赖

**Comment by Kingtous** [comment]
方便snap测试吗，`snap install rustplayer --devmode`

**Comment by Kingtous** [comment]
默认已解决。互联网电台已并入主分支。

**Comment by sharkocha** [comment]
> 默认已解决。互联网电台已并入主分支。

好勒 不好意思最近实在太忙 没及时回复

**Comment by RookieOHY** [comment]
> > 可以试试分支feat/radio，目前测试了下两个新闻m3u8电台源，可以正常播放。 现在没有打静态包，需要ffmpeg的dev依赖，arch好像直接装ffmpeg就行。 按h进入help界面后，按r打开`radio.ini`可以添加m3u8源。 项目根目录有个radio.ini，里面有两个新闻测试源，可以粘贴进去试试。 格式： [name]\s[m3u8 url]
> 
> 在arch里面编译失败了，倒是装了ffmpeg，不过我不了解rust，没办法确定具体原因，主要的error显示为这个：
> 
> error: failed to run custom build command for `ffmpeg-sys-next v4.4.0`
> 
> 估计是因为直接装ffmpeg不太行

请问如何测试互联网电台呢 ？粘贴url到哪一个地方呢

**Comment by Kingtous** [comment]
> > > 可以试试分支feat/radio，目前测试了下两个新闻m3u8电台源，可以正常播放。 现在没有打静态包，需要ffmpeg的dev依赖，arch好像直接装ffmpeg就行。 按h进入help界面后，按r打开`radio.ini`可以添加m3u8源。 项目根目录有个radio.ini，里面有两个新闻测试源，可以粘贴进去试试。 格式： [name]\s[m3u8 url]
> > 
> > 在arch里面编译失败了，倒是装了ffmpeg，不过我不了解rust，没办法确定具体原因，主要的error显示为这个：
> > 
> > error: failed to run custom build command for `ffmpeg-sys-next v4.4.0`
> > 
> > 估计是因为直接装ffmpeg不太行
> 
> 请问如何测试互联网电台呢 ？粘贴url到哪一个地方呢

arch下可以用fix/arch分支

**Comment by RookieOHY** [comment]
> > > > 可以试试分支feat/radio，目前测试了下两个新闻m3u8电台源，可以正常播放。 现在没有打静态包，需要ffmpeg的dev依赖，arch好像直接装ffmpeg就行。 按h进入help界面后，按r打开`radio.ini`可以添加m3u8源。 项目根目录有个radio.ini，里面有两个新闻测试源，可以粘贴进去试试。 格式： [name]\s[m3u8 url]
> > > 
> > > 
> > > 在arch里面编译失败了，倒是装了ffmpeg，不过我不了解rust，没办法确定具体原因，主要的error显示为这个：
> > > error: failed to run custom build command for `ffmpeg-sys-next v4.4.0`
> > > 估计是因为直接装ffmpeg不太行
> > 
> > 
> > 请问如何测试互联网电台呢 ？粘贴url到哪一个地方呢
> 
> arch下可以用fix/arch分支

windows呢 没有找到可以粘贴的地方
