### ISSUE TITLE
不能记忆音量大小

### ISSUE THREAD

**Issue by LUKE-GG33** [Kingtous/RustPlayer#6]
当播放下一曲时，音量会重置为最大
系统：Archlinux wayland
终端：Alacritty
声音系统：PipeWire

**Comment by Kingtous** [comment]
可以测试一下，最新版本已修复该问题。

注意：最新版本加入了ffmpeg依赖，用于m3u8广播解码。推荐arch系使用snap安装

**Comment by LUKE-GG33** [comment]
`RustPlayer: error while loading shared libraries: libavutil.so.55: cannot open shared object file: No such file or directory`
抱歉回复晚了，貌似arch的ffmpeg太新了，无法运行。

**Comment by Kingtous** [comment]
可以使用snap安装


------------------ 原始邮件 ------------------
发件人: luke ***@***.***&gt;
发送时间: 2022年5月7日 02:38
收件人: Kingtous/RustPlayer ***@***.***&gt;
抄送: Kingtous ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[Kingtous/RustPlayer] 不能记忆音量大小 (Issue #6)





 
RustPlayer: error while loading shared libraries: libavutil.so.55: cannot open shared object file: No such file or directory
 抱歉回复晚了，貌似arch的ffmpeg太新了。

**Comment by LUKE-GG33** [comment]
> 可以使用snap安装
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: luke ***@***.***&gt;
> 发送时间: 2022年5月7日 02:38
> 收件人: Kingtous/RustPlayer ***@***.***&gt;
> 抄送: Kingtous ***@***.***&gt;, Comment ***@***.***&gt;
> 主题: 回复：[Kingtous/RustPlayer] 不能记忆音量大小 (Issue #6)
> 
> 
> 
> 
> 
>  
> RustPlayer: error while loading shared libraries: libavutil.so.55: cannot open shared object file: No such file or directory
>  抱歉回复晚了，貌似arch的ffmpeg太新了。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

使用snapd确实可以安装，二进制因为ffmpeg依赖的问题，无法运行，能否开一个本地离线播放器的分支。最近pipewire在改动，没法测试音量相关

**Comment by Kingtous** [comment]
> 

可以的。对了，可以试试[fix/arch](https://github.com/Kingtous/RustPlayer/tree/fix/arch)分支。这个适配的是arch环境下的ffmpeg。

**Comment by LUKE-GG33** [comment]
> > 
> 
> 可以的。对了，可以试试[fix/arch](https://github.com/Kingtous/RustPlayer/tree/fix/arch)分支。这个适配的是arch环境下的ffmpeg。

感谢，up幸苦了。
发现使用方向键添加单首歌曲到播放列表不会重置音量，使用回车批量添加会重置音量。
